import profiles from './maineLoadProfiles.json';
import type { HeatingFuel, HomeType } from './types';

/**
 * Maine home 5–9 PM weekday electric load, from NREL ResStock 2024 r2 (TMY3).
 * The bundled table (lib/maineLoadProfiles.json) is generated by
 * scripts/generate_load_table.py — see that file for the methodology.
 */

export const HOME_TYPES = profiles.types as HomeType[];
export const HEATING_FUELS = profiles.fuels as HeatingFuel[];

/** Human-friendly labels for the heating-fuel options. */
export const HEATING_FUEL_LABELS: Record<HeatingFuel, string> = {
  Electricity: 'Electric',
  'Natural Gas': 'Natural Gas',
  'Fuel Oil': 'Fuel Oil',
  Propane: 'Propane',
  'Other Fuel': 'Wood / Other',
};

const VINTAGES = profiles.vintages;

/** Map a build year to a ResStock vintage band. */
export function yearToVintage(year: number): string {
  if (year < 1940) return '<1940';
  if (year >= 2010) return '2010s';
  const decade = Math.floor(year / 10) * 10; // 1940, 1950, …, 2000
  return `${decade}s`;
}

/** Map floor area to a ResStock sqft bin. */
export function sqftToBin(sqft: number): string {
  if (sqft < 1500) return '0-1499';
  if (sqft < 2500) return '1500-2499';
  if (sqft < 4000) return '2500-3999';
  return '4000+';
}

const table = profiles.table as Record<string, { kw: number; n: number; level: string }>;

/** Estimated 5–9 PM weekday electric load (kW) for a home. */
export function lookupHomePeakLoad(
  homeType: HomeType,
  yearBuilt: number,
  sqft: number,
  heatingFuel: HeatingFuel,
): number {
  const vintage = VINTAGES.includes(yearToVintage(yearBuilt))
    ? yearToVintage(yearBuilt)
    : VINTAGES[VINTAGES.length - 1];
  const key = `${homeType}|${vintage}|${sqftToBin(sqft)}|${heatingFuel}`;
  return table[key]?.kw ?? 0;
}
